title: "Exaloop blog"
description: "&copy; 2023 Exaloop, Inc. All rights reserved."
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: false          # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.html"}
  - {file: "archive.html"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: GitHub, icon: "fa-brands fa-github", url: "https://github.com/exaloop"}
  - {title: Twitter, icon: "fa-brands fa-twitter", url: "https://twitter.com/exaloop"}
  - {title: Mail, icon: "fa-solid fa-envelope", url: "mailto:info@exaloop.io"}
  - {title: Subscribe, icon: "fa-solid fa-rss", url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
 - jekyll-redirect-from
